# Generated by Django 5.0.7 on 2024-10-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_item_service_expense_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participantexpense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
